version: '3.9'
services:
  inery-node:
    container_name: inery-node
    image: alteregogi/inery-node
    init: true
    build:
      context: https://github.com/alteregogi/inery-node-docker.git
        
      args:
        INERY_ACCOUNT_NAME: REPLACE_WITH_YOUR_INERY_ACC
        INERY_PUBLIC_KEY: REPLACE_WITH_YOUR_PUB_KEY
        INERY_PRIVATE_KEY: REPLACE_WITH_YOUR_PRIV_KEY
        NODE_IP_ADDRESS: REPLACE_WITH_YOUR_IP_ADDR
      
    command: "tail -f /dev/null"
    privileged: true
    ports:
      - 9010:9010
      - 8888:8888
    volumes:
      - inery-node-docker:/inery-node/
    environment:
      PUID: 1000
      GUID: 1000

volumes:
  inery-node-docker:
    name: inery-node-docker
    driver: local
    driver_opts:
      type: none
      device: "${HOME}/inery/inery-node-vol/"
      o: bind
